default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        files: "^kitsune/"
        exclude: "^.*/migrations/.*$|kitsune/sumo/db_strings.py"
        language_version: python3.11
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.2.0
          - prettier-plugin-svelte@3.1.2
        files: "^svelte/"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.12.0
    hooks:
      - id: mypy
        # Add to the "additional_dependencies" list below any poetry
        # dependencies or their stub packages that provide type hints.
        additional_dependencies:
          - boto3-stubs==1.34.17
          - types-redis==4.6.0.20240106
          - types-requests==2.31.0.20240106
          - types-bleach==6.1.0.1
          - types-python-dateutil==2.8.19.20240106
          - types-simplejson==3.19.0.2
        files: "^kitsune/"
        exclude: "/migrations/"

  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v8.1.0
  #   hooks:
  #     - id: eslint
  #       args: [--no-eslintrc, --config=webpack/eslintrc.js]
  #       exclude: "webpack/.*|webpack\\..*\\.js"
  #       additional_dependencies:
  #         - eslint@8.1.0
  #         - eslint-import-resolver-webpack@0.13.2
  #         - eslint-plugin-import@2.25.2
